version: '3.4'

services:
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
  database:
    image: mysql:latest
    networks:
        new:
         aliases:
          - mysql-container
    ports:
        - "3306:3306"
    expose: 
        - 3306
    volumes:
        - db-volume:/var/lib/mysqll
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: G@briel123
        MYSQL_DATABASE: userapi
volumes:
  db-volume:
