version: '3.4'

services:
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
  database:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UserAPI
      MYSQL_USER: mysqlDbUser
      MYSQL_PASSWORD: mysqlDbPass#
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

volumes:
  db-volume:
